apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-server
  labels: 
    app: python-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-http-server
  template:
    metadata:
      labels:
        app: python-http-server
    spec:
      containers:
      - name: python-http-server
        image: bobcrutchley/python-http-server:latest
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /
            port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: python-http-server
spec:
  selector:
    app: python-http-server
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: LoadBalancer
